# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: single_log.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import log_pb2 as log__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='single_log.proto',
  package='bce.cds',
  syntax='proto2',
  serialized_pb=_b('\n\x10single_log.proto\x12\x07\x62\x63\x65.cds\x1a\tlog.proto\".\n\nRGLogIndex\x12\r\n\x05rg_id\x18\x01 \x02(\t\x12\x11\n\tlog_index\x18\x02 \x02(\x03\"R\n\rSingleLogMeta\x12\x15\n\rfirst_log_fno\x18\x01 \x02(\x03\x12*\n\rfirst_indexes\x18\x02 \x03(\x0b\x32\x13.bce.cds.RGLogIndex\"_\n\x17SingleLogWriteDataIndex\x12\x14\n\x0ctmpfs_offset\x18\x01 \x02(\x04\x12\x14\n\x0ctmpfs_length\x18\x02 \x02(\x04\x12\x18\n\x10real_data_length\x18\x03 \x02(\x04\"\xac\x01\n\rRGEntryHeader\x12\r\n\x05rg_id\x18\x01 \x02(\t\x12\r\n\x05index\x18\x02 \x02(\x03\x12\x0c\n\x04term\x18\x03 \x02(\x03\x12\x0c\n\x04type\x18\x04 \x02(\x05\x12\x10\n\x08\x64\x61ta_len\x18\x05 \x02(\x05\x12\x13\n\x0bspace_index\x18\x06 \x01(\x04\x12:\n\x10write_data_index\x18\x07 \x01(\x0b\x32 .bce.cds.SingleLogWriteDataIndex')
  ,
  dependencies=[log__pb2.DESCRIPTOR,])




_RGLOGINDEX = _descriptor.Descriptor(
  name='RGLogIndex',
  full_name='bce.cds.RGLogIndex',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rg_id', full_name='bce.cds.RGLogIndex.rg_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='log_index', full_name='bce.cds.RGLogIndex.log_index', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=86,
)


_SINGLELOGMETA = _descriptor.Descriptor(
  name='SingleLogMeta',
  full_name='bce.cds.SingleLogMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_log_fno', full_name='bce.cds.SingleLogMeta.first_log_fno', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='first_indexes', full_name='bce.cds.SingleLogMeta.first_indexes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=170,
)


_SINGLELOGWRITEDATAINDEX = _descriptor.Descriptor(
  name='SingleLogWriteDataIndex',
  full_name='bce.cds.SingleLogWriteDataIndex',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tmpfs_offset', full_name='bce.cds.SingleLogWriteDataIndex.tmpfs_offset', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tmpfs_length', full_name='bce.cds.SingleLogWriteDataIndex.tmpfs_length', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='real_data_length', full_name='bce.cds.SingleLogWriteDataIndex.real_data_length', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=267,
)


_RGENTRYHEADER = _descriptor.Descriptor(
  name='RGEntryHeader',
  full_name='bce.cds.RGEntryHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rg_id', full_name='bce.cds.RGEntryHeader.rg_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index', full_name='bce.cds.RGEntryHeader.index', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='term', full_name='bce.cds.RGEntryHeader.term', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='bce.cds.RGEntryHeader.type', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_len', full_name='bce.cds.RGEntryHeader.data_len', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='space_index', full_name='bce.cds.RGEntryHeader.space_index', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='write_data_index', full_name='bce.cds.RGEntryHeader.write_data_index', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=442,
)

_SINGLELOGMETA.fields_by_name['first_indexes'].message_type = _RGLOGINDEX
_RGENTRYHEADER.fields_by_name['write_data_index'].message_type = _SINGLELOGWRITEDATAINDEX
DESCRIPTOR.message_types_by_name['RGLogIndex'] = _RGLOGINDEX
DESCRIPTOR.message_types_by_name['SingleLogMeta'] = _SINGLELOGMETA
DESCRIPTOR.message_types_by_name['SingleLogWriteDataIndex'] = _SINGLELOGWRITEDATAINDEX
DESCRIPTOR.message_types_by_name['RGEntryHeader'] = _RGENTRYHEADER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RGLogIndex = _reflection.GeneratedProtocolMessageType('RGLogIndex', (_message.Message,), dict(
  DESCRIPTOR = _RGLOGINDEX,
  __module__ = 'single_log_pb2'
  # @@protoc_insertion_point(class_scope:bce.cds.RGLogIndex)
  ))
_sym_db.RegisterMessage(RGLogIndex)

SingleLogMeta = _reflection.GeneratedProtocolMessageType('SingleLogMeta', (_message.Message,), dict(
  DESCRIPTOR = _SINGLELOGMETA,
  __module__ = 'single_log_pb2'
  # @@protoc_insertion_point(class_scope:bce.cds.SingleLogMeta)
  ))
_sym_db.RegisterMessage(SingleLogMeta)

SingleLogWriteDataIndex = _reflection.GeneratedProtocolMessageType('SingleLogWriteDataIndex', (_message.Message,), dict(
  DESCRIPTOR = _SINGLELOGWRITEDATAINDEX,
  __module__ = 'single_log_pb2'
  # @@protoc_insertion_point(class_scope:bce.cds.SingleLogWriteDataIndex)
  ))
_sym_db.RegisterMessage(SingleLogWriteDataIndex)

RGEntryHeader = _reflection.GeneratedProtocolMessageType('RGEntryHeader', (_message.Message,), dict(
  DESCRIPTOR = _RGENTRYHEADER,
  __module__ = 'single_log_pb2'
  # @@protoc_insertion_point(class_scope:bce.cds.RGEntryHeader)
  ))
_sym_db.RegisterMessage(RGEntryHeader)


# @@protoc_insertion_point(module_scope)
