# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sparse_storage_engine.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sparse_storage_engine.proto',
  package='bce.cds',
  syntax='proto2',
  serialized_pb=_b('\n\x1bsparse_storage_engine.proto\x12\x07\x62\x63\x65.cds\x1a\x0c\x63ommon.proto\"p\n\x15SparseFileSegmentMeta\x12\r\n\x05inode\x18\x01 \x02(\x04\x12\x1a\n\x12\x66ile_segment_index\x18\x02 \x02(\x05\x12\x18\n\x10\x64isk_slice_index\x18\x03 \x02(\x05\x12\x12\n\ncache_mode\x18\x04 \x02(\x05\"4\n\x0eSparseFileMeta\x12\r\n\x05inode\x18\x01 \x02(\x04\x12\x13\n\x0b\x63reate_time\x18\x02 \x02(\x04\",\n\x06Rename\x12\x10\n\x08old_path\x18\x01 \x02(\t\x12\x10\n\x08new_path\x18\x02 \x02(\t\"J\n\x19SparseFileSystemOperation\x12\x0c\n\x04type\x18\x01 \x02(\x05\x12\x1f\n\x06rename\x18\x02 \x01(\x0b\x32\x0f.bce.cds.Rename\"_\n\x0fSparseInodeMeta\x12\r\n\x05inode\x18\x01 \x02(\x04\x12\r\n\x05paths\x18\x02 \x03(\t\x12.\n\x06slices\x18\x03 \x03(\x0b\x32\x1e.bce.cds.SparseFileSegmentMetaB\x03\x80\x01\x01')
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_SPARSEFILESEGMENTMETA = _descriptor.Descriptor(
  name='SparseFileSegmentMeta',
  full_name='bce.cds.SparseFileSegmentMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='inode', full_name='bce.cds.SparseFileSegmentMeta.inode', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_segment_index', full_name='bce.cds.SparseFileSegmentMeta.file_segment_index', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disk_slice_index', full_name='bce.cds.SparseFileSegmentMeta.disk_slice_index', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cache_mode', full_name='bce.cds.SparseFileSegmentMeta.cache_mode', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=166,
)


_SPARSEFILEMETA = _descriptor.Descriptor(
  name='SparseFileMeta',
  full_name='bce.cds.SparseFileMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='inode', full_name='bce.cds.SparseFileMeta.inode', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='create_time', full_name='bce.cds.SparseFileMeta.create_time', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=220,
)


_RENAME = _descriptor.Descriptor(
  name='Rename',
  full_name='bce.cds.Rename',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='old_path', full_name='bce.cds.Rename.old_path', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new_path', full_name='bce.cds.Rename.new_path', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=266,
)


_SPARSEFILESYSTEMOPERATION = _descriptor.Descriptor(
  name='SparseFileSystemOperation',
  full_name='bce.cds.SparseFileSystemOperation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='bce.cds.SparseFileSystemOperation.type', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rename', full_name='bce.cds.SparseFileSystemOperation.rename', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=342,
)


_SPARSEINODEMETA = _descriptor.Descriptor(
  name='SparseInodeMeta',
  full_name='bce.cds.SparseInodeMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='inode', full_name='bce.cds.SparseInodeMeta.inode', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='paths', full_name='bce.cds.SparseInodeMeta.paths', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='slices', full_name='bce.cds.SparseInodeMeta.slices', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=439,
)

_SPARSEFILESYSTEMOPERATION.fields_by_name['rename'].message_type = _RENAME
_SPARSEINODEMETA.fields_by_name['slices'].message_type = _SPARSEFILESEGMENTMETA
DESCRIPTOR.message_types_by_name['SparseFileSegmentMeta'] = _SPARSEFILESEGMENTMETA
DESCRIPTOR.message_types_by_name['SparseFileMeta'] = _SPARSEFILEMETA
DESCRIPTOR.message_types_by_name['Rename'] = _RENAME
DESCRIPTOR.message_types_by_name['SparseFileSystemOperation'] = _SPARSEFILESYSTEMOPERATION
DESCRIPTOR.message_types_by_name['SparseInodeMeta'] = _SPARSEINODEMETA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SparseFileSegmentMeta = _reflection.GeneratedProtocolMessageType('SparseFileSegmentMeta', (_message.Message,), dict(
  DESCRIPTOR = _SPARSEFILESEGMENTMETA,
  __module__ = 'sparse_storage_engine_pb2'
  # @@protoc_insertion_point(class_scope:bce.cds.SparseFileSegmentMeta)
  ))
_sym_db.RegisterMessage(SparseFileSegmentMeta)

SparseFileMeta = _reflection.GeneratedProtocolMessageType('SparseFileMeta', (_message.Message,), dict(
  DESCRIPTOR = _SPARSEFILEMETA,
  __module__ = 'sparse_storage_engine_pb2'
  # @@protoc_insertion_point(class_scope:bce.cds.SparseFileMeta)
  ))
_sym_db.RegisterMessage(SparseFileMeta)

Rename = _reflection.GeneratedProtocolMessageType('Rename', (_message.Message,), dict(
  DESCRIPTOR = _RENAME,
  __module__ = 'sparse_storage_engine_pb2'
  # @@protoc_insertion_point(class_scope:bce.cds.Rename)
  ))
_sym_db.RegisterMessage(Rename)

SparseFileSystemOperation = _reflection.GeneratedProtocolMessageType('SparseFileSystemOperation', (_message.Message,), dict(
  DESCRIPTOR = _SPARSEFILESYSTEMOPERATION,
  __module__ = 'sparse_storage_engine_pb2'
  # @@protoc_insertion_point(class_scope:bce.cds.SparseFileSystemOperation)
  ))
_sym_db.RegisterMessage(SparseFileSystemOperation)

SparseInodeMeta = _reflection.GeneratedProtocolMessageType('SparseInodeMeta', (_message.Message,), dict(
  DESCRIPTOR = _SPARSEINODEMETA,
  __module__ = 'sparse_storage_engine_pb2'
  # @@protoc_insertion_point(class_scope:bce.cds.SparseInodeMeta)
  ))
_sym_db.RegisterMessage(SparseInodeMeta)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\200\001\001'))
# @@protoc_insertion_point(module_scope)
